### ISSUE TITLE
Commits and all that

### ISSUE THREAD

**Issue by lukehamel7** [Cubemaster7/OrbicTextAdventure#4]
So it turns out Github doesn't automatically combine commits if one was started before the other but finished after the other. It might be a good idea to have a separate branches, and then we can use pull requests to combine them (Which keeps as much as it can).

**Comment by connor-j-jordan** [comment]
Alright - would you like to start that now?

**Comment by connor-j-jordan** [comment]
And, does it work so far? In the other website?

**Comment by lukehamel7** [comment]
It worked when I made the first release, except for the title screen which won't be a problem on a desktop
